global:
  scrape_interval: 15s
remote_write:
  - url: https://prometheus-prod-37-prod-ap-southeast-1.grafana.net/api/prom/push
    basic_auth:
      username: # Remove due to security issue
      password: # Remove due to security issue
scrape_configs:
  - job_name: usdt_indexer
    static_configs:
      - targets: ["localhost:8000"]

  - job_name: "geth_node_1"
    static_configs:
      - targets: ["localhost:51921"]
        labels:
          group: "Mission4"
  - job_name: "geth_node_2"
    static_configs:
      - targets: ["localhost:52009"]
        labels:
          group: "Mission4"
